version: "3.7"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.4.14'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper:/bitnami/zookeeper