dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    check-serializable: false
    serialize-check-status: DISABLE
  protocol:
    name: dubbo
    port: -1
    serialization: fastjson2
  registry:
    address: zookeeper://127.0.0.1:2181